name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release-please:
    uses: seventwo-studio/.github/.github/workflows/release-please.yml@94665c6663d78c16a3b174e3513bb4a2ff06c4e8
    with:
      client-id: ${{ vars.RELEASE_APP_CLIENT_ID }}
    secrets:
      private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
